--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Slayer-Return/DisableEnchantingTable
build-by-default: true
branches:
- main
projects:
  DisableEnchantingTable:
    path: ""
    icon: "book.png"
...
